name: ci

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  ci:
    uses: takey7/ai-dev-platform-requirements-2026-04-14/.github/workflows/ci.yml@v0.1.5
    with:
      manifest_path: .platform/platform.yaml
    secrets: inherit
