name: ci

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  ci:
    uses: {{SOURCE_REPO}}/.github/workflows/ci.yml@{{SOURCE_REF}}
    with:
      manifest_path: .platform/platform.yaml
    secrets: inherit
