name: security-scan

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  security-scan:
    uses: {{SOURCE_REPO}}/.github/workflows/security-scan.yml@{{SOURCE_REF}}
    with:
      manifest_path: .platform/platform.yaml
      base_ref: ${{ github.base_ref || github.event.merge_group.base_ref || github.event.repository.default_branch }}
    secrets: inherit
